language: elixir
elixir:
  - 1.3
otp_release:
  - 18.3
sudo: false
addons:
  postgresql: '9.4' # Use postgres 9.4
  before_script:
    # Create the test database
    - psql -c 'create database reverie_test;' -U postgres
